import { FormEvent, useEffect, useMemo, useState } from 'react'
import { BookOpen, ChevronDown, ChevronRight, Home, Plus } from 'lucide-react'
import { useLibrary } from '../context/LibraryContext'
import { createLocation, getLocations } from '../lib/libraryApi'
import type { LibraryLocation } from '../lib/models'

export function ShelvesPage(){const {activeLibrary}=useLibrary();const [locations,setLocations]=useState<LibraryLocation[]>([]);const [creating,setCreating]=useState(false);const [name,setName]=useState('');const [type,setType]=useState('room');const [parent,setParent]=useState('');const [open,setOpen]=useState<string[]>([]);const [error,setError]=useState<string|null>(null)
 async function load(){if(!activeLibrary)return;try{setLocations(await getLocations(activeLibrary.id))}catch(e){setError(e instanceof Error?e.message:'Error al cargar ubicaciones')}} useEffect(()=>{void load()},[activeLibrary])
 const roots=useMemo(()=>locations.filter(l=>!l.parentId),[locations]); const children=(id:string)=>locations.filter(l=>l.parentId===id)
 async function submit(e:FormEvent){e.preventDefault();if(!activeLibrary||!name.trim())return;try{await createLocation(activeLibrary.id,{name,type,parentId:parent||null});setName('');setParent('');setCreating(false);await load()}catch(err){setError(err instanceof Error?err.message:'No se pudo crear la ubicación')}}
 function Node({loc,depth=0}:{loc:LibraryLocation;depth?:number}){const kids=children(loc.id);const expanded=open.includes(loc.id);return <div className="location-node" style={{marginLeft:depth*12}}><button className="shelf-header" onClick={()=>setOpen(o=>expanded?o.filter(x=>x!==loc.id):[...o,loc.id])}><span>{depth===0?<Home size={18}/>:<BookOpen size={17}/>}<strong>{loc.name}</strong><small>{loc.type} · {loc.bookCount} libros</small></span>{kids.length?(expanded?<ChevronDown/>:<ChevronRight/>):null}</button>{expanded&&kids.map(k=><Node key={k.id} loc={k} depth={depth+1}/>)}</div>}
 return <div className="page"><p className="eyebrow">LOCALIZACIÓN</p><h1>Estanterías</h1><p className="subtitle">Organiza la colección como un inventario físico.</p><button className="primary-button top-action" onClick={()=>setCreating(v=>!v)}><Plus size={18}/> Crear ubicación</button>
 {creating&&<form className="form-card" onSubmit={submit}><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Salón, Librería roble, Balda 1"/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="property">Casa / espacio</option><option value="room">Habitación</option><option value="bookcase">Estantería</option><option value="shelf">Balda</option><option value="other">Otro</option></select></label><label>Dentro de<select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Nivel principal</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button className="primary-button">Guardar ubicación</button></form>}
 {error&&<div className="form-message error">{error}</div>}{!locations.length?<div className="empty-library"><div>🗄️</div><h2>Aún no has creado ubicaciones</h2><p>Crea primero una habitación o espacio y después añade estanterías y baldas dentro.</p></div>:<div className="shelf-list">{roots.map(r=><section className="shelf-card" key={r.id}><Node loc={r}/></section>)}</div>}</div>}
